Repository qiskit-community/qiskit-finance, pull requests merged in 2021-08, with the labels that each got.

#85 Bump reno requirement to latest version and set default_branch
  releasenotes/config.yaml
  requirements-dev.txt
Labels: automerge, stable backport potential

#88 Fix confidence interval in Asian Barrier Spread tutorial
  docs/tutorials/07_asian_barrier_spread_pricing.ipynb
  test/data_providers/test_data_providers.py
Labels: stable backport potential

#90 Basic QAE tutorial
  .pylintdict
  docs/tutorials/00_amplitude_estimation.ipynb
Labels: stable backport potential, automerge

#92 Add Windows/Mac to CI
  .github/actions/install-libraries/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: stable backport potential, type: enhancement, type: ci

#93 [Stable] Add Windows/Mac to CI (#92)
  .github/actions/install-libraries/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: type: enhancement, automerge, type: ci

#94 Fix lint errors
  qiskit_finance/data_providers/exchange_data_provider.py
  qiskit_finance/data_providers/wikipedia_data_provider.py
  qiskit_finance/version.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: stable backport potential, type: bug, priority: high

#96 Fix docs release notes search
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: type: documentation, priority: high

#97 [Stable] Fix docs release notes search (#96)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: type: documentation, priority: high

#99 Fix unit test failure due to new Aer
  test/circuit/test_european_call_delta_objective.py
  test/circuit/test_european_call_pricing_objective.py
Labels: type: bug
