Repository qiskit-community/qiskit-finance, pull requests merged in 2021-09, with the labels that each got.

#100 Improve project setup long-description & Ignore untagged release notes on docs.upload
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  README.md
  setup.py
  tools/ignore_untagged_notes.sh
Labels: type: documentation, type: enhancement

#101 [Stable] Improve project setup long-description & Ignore untagged release notes on docs.upload (#100)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  README.md
  setup.py
  tools/ignore_untagged_notes.sh
Labels: type: documentation, type: enhancement

#102 Disable pylint consider-using-f-string for now
  .pylintrc
Labels: type: bug, priority: high

#104 Re-enable lint f-string check
  .pylintrc
  README.md
  qiskit_finance/applications/optimization/portfolio_diversification.py
  qiskit_finance/circuit/library/probability_distributions/normal.py
  qiskit_finance/data_providers/data_on_demand_provider.py
  qiskit_finance/data_providers/exchange_data_provider.py
  qiskit_finance/data_providers/wikipedia_data_provider.py
  qiskit_finance/data_providers/yahoo_data_provider.py
  qiskit_finance/version.py
  test/applications/test_portfolio_diversification.py
  test/circuit/test_european_call_delta_objective.py
  test/circuit/test_european_call_pricing_objective.py
  test/circuit/test_fixed_income_pricing_objective.py
  test/data_providers/test_data_providers.py
  test/finance_test_case.py
  test/test_readme_sample.py
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
  tools/verify_headers.py
Labels: type: qa

#106 Fixing the translations script that was breaking the translated docs publish build
  tools/deploy_translatable_strings.sh
Labels: stable backport potential, automerge
