Repository qiskit-community/qiskit-finance, pull requests merged in 2021-07, with the labels that each got.

#67 Preparing docs & tutorials for translations
  .github/workflows/deploy-docs.yml
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#68 [Stable] Add Getting Started Documentation & Prepare doc & tutorials for translations
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  docs/_templates/versions.html
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/index.rst
  docs/versionutils.py
  qiskit_finance/circuit/library/probability_distributions/lognormal.py
  qiskit_finance/circuit/library/probability_distributions/normal.py
  requirements-dev.txt
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#75 Pin networkx
  requirements-dev.txt
Labels: priority: critical, stable backport potential, type: bug

#73 Updating the translation deploy script
  docs/conf.py
  tools/deploy_translatable_strings.sh
Labels: stable backport potential

#78 Streamline CI
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#79 [Stable] Streamline CI (#78)
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#80 Handle new yfinance, fix bugs in provider
  docs/tutorials/11_time_series.ipynb
  qiskit_finance/data_providers/yahoo_data_provider.py
  releasenotes/notes/yahoo-ccd9beea8bb60fd9.yaml
  requirements.txt
  test/data_providers/test_data_providers.py
Labels: Changelog: Bugfix, automerge, stable backport potential, type: bug

#82 Add link to repo tutorial on html tutorial prolog
  docs/conf.py
Labels: stable backport potential, type: documentation, type: enhancement
