Repository qiskit-community/qiskit-finance, pull requests merged in 2021-06, with the labels that each got.

#56 Install types-certifi on requirements-dev.txt
  requirements-dev.txt
Labels: priority: critical, type: bug

#59 Docs - Remove non overidden base methods/attributes from classes
  docs/_templates/autosummary/class.rst
Labels: type: documentation

#63 Move away from using pylint header plugin
  .github/workflows/main.yml
  .pylintdict
  .pylintrc
  Makefile
  requirements-dev.txt
  tools/verify_headers.py
  tox.ini
Labels: type: enhancement

#62 Fix tutorial hyperlinks and title formatting (#60)
  .pylintdict
  docs/tutorials/01_portfolio_optimization.ipynb
  docs/tutorials/02_portfolio_diversification.ipynb
  docs/tutorials/03_european_call_option_pricing.ipynb
  docs/tutorials/04_european_put_option_pricing.ipynb
  docs/tutorials/05_bull_spread_pricing.ipynb
  docs/tutorials/06_basket_option_pricing.ipynb
  docs/tutorials/07_asian_barrier_spread_pricing.ipynb
  docs/tutorials/08_fixed_income_pricing.ipynb
  docs/tutorials/09_credit_risk_analysis.ipynb
  docs/tutorials/10_qgan_option_pricing.ipynb
  docs/tutorials/11_time_series.ipynb
Labels: type: documentation
