Repository qiskit-community/qiskit-finance, pull requests merged in 2022-06, with the labels that each got.

#170 Pin pylint to < 2.14.0
  .github/workflows/main.yml
  requirements-dev.txt
Labels: priority: high, type: ci

#173 Add .editorconfig
  .editorconfig
Labels: type: qa

#174 Drop `pandas` requirement restriction
  releasenotes/notes/pandas-restriction-0965815429fd8877.yaml
  requirements.txt
Labels: stable backport potential

#179 Add overview to docs
  docs/index.rst
Labels: stable backport potential, type: documentation, type: enhancement

#181 Fix Aer Deprecate Messages
  test/circuit/test_european_call_delta_objective.py
  test/circuit/test_european_call_pricing_objective.py
  test/circuit/test_fixed_income_pricing_objective.py
Labels: type: ci

#182 Remove pbark as a code owner
  .github/CODEOWNERS
Labels: stable backport potential

#186 switched to sphinx-design
  docs/conf.py
  docs/getting_started.rst
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge
