Repository qiskit-community/qiskit-finance, pull requests merged in 2022-03, with the labels that each got.

#151 Bump black version and relax constraint
  docs/tutorials/02_portfolio_diversification.ipynb
  docs/tutorials/03_european_call_option_pricing.ipynb
  docs/tutorials/04_european_put_option_pricing.ipynb
  docs/tutorials/05_bull_spread_pricing.ipynb
  docs/tutorials/06_basket_option_pricing.ipynb
  docs/tutorials/07_asian_barrier_spread_pricing.ipynb
  docs/tutorials/09_credit_risk_analysis.ipynb
  docs/tutorials/10_qgan_option_pricing.ipynb
  qiskit_finance/circuit/library/payoff_functions/european_call_delta_objective.py
  qiskit_finance/circuit/library/payoff_functions/fixed_income_pricing_objective.py
  qiskit_finance/circuit/library/probability_distributions/gaussian_conditional_independence_model.py
  qiskit_finance/circuit/library/probability_distributions/lognormal.py
  qiskit_finance/circuit/library/probability_distributions/normal.py
  requirements-dev.txt
  test/applications/test_european_call_delta.py
  test/circuit/test_european_call_delta_objective.py
Labels: type: enhancement

#152 Adopt lazy imports from Terra
  qiskit_finance/data_providers/exchange_data_provider.py
  qiskit_finance/data_providers/random_data_provider.py
  qiskit_finance/data_providers/wikipedia_data_provider.py
  qiskit_finance/data_providers/yahoo_data_provider.py
  requirements.txt
  test/__init__.py
  test/circuit/test_european_call_delta_objective.py
  test/circuit/test_european_call_pricing_objective.py
  test/circuit/test_fixed_income_pricing_objective.py
  test/data_providers/test_data_providers.py
  test/finance_test_case.py
Labels: type: enhancement, run_slow

#155 Preparing to publish Japanese docs
  docs/versionutils.py
Labels: stable backport potential, automerge

#157 Documentation fixes
  docs/tutorials/03_european_call_option_pricing.ipynb
  docs/tutorials/04_european_put_option_pricing.ipynb
  docs/tutorials/05_bull_spread_pricing.ipynb
  docs/tutorials/06_basket_option_pricing.ipynb
  docs/tutorials/07_asian_barrier_spread_pricing.ipynb
  docs/tutorials/08_fixed_income_pricing.ipynb
  docs/tutorials/09_credit_risk_analysis.ipynb
  qiskit_finance/circuit/library/probability_distributions/lognormal.py
  test/circuit/test_european_call_delta_objective.py
Labels: stable backport potential, type: documentation

#159 Pin Jinja2 used by Sphinx
  requirements-dev.txt
Labels: stable backport potential, type: bug, type: documentation, priority: high

#162 Unpin Jinja2
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge
