Repository qiskit-community/qiskit-finance, pull requests merged in 2022-11, with the labels that each got.

#217 Correct Yahoo provider unit test result
  test/data_providers/test_data_providers.py
Labels: type: ci

#218 Add Spanish to language switcher
  docs/versionutils.py
Labels: stable backport potential

#220 Ignore untagged reno notes on documentation
  tools/ignore_untagged_notes.sh
Labels: stable backport potential, automerge, type: ci

#222 remove ENHANCEMENT_REQUEST issue template
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.yaml
Labels: automerge

#224 Update docs to use new sphinx theme
  .github/workflows/main.yml
  docs/_templates/layout.html
  docs/conf.py
  requirements-dev.txt
  test/data_providers/test_data_providers.py
Labels: stable backport potential, type: documentation
