Repository qiskit-community/qiskit-finance, pull requests merged in 2022-01, with the labels that each got.

#126 Fix mypy errors created with latest numpy
  qiskit_finance/data_providers/_base_data_provider.py
Labels: stable backport potential, type: bug, priority: high, type: ci

#128 Pin sphinx-autodoc-typehints to unblock docs builds
  requirements-dev.txt
Labels: stable backport potential, type: bug, priority: high, automerge, type: ci

#130 Fix copyright check when rebasing
  tools/check_copyright.py
Labels: stable backport potential, type: bug, automerge, type: ci

#133 Pandas 1.4.0 breaks Yahoo Finance library
  requirements.txt
Labels: stable backport potential, type: bug, priority: high

#132 Add support for Python 3.10
  .github/actions/install-finance/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  pyproject.toml
  releasenotes/notes/add-python310-support-c0771fca614b0cde.yaml
  setup.py
  tox.ini
Labels: type: enhancement

#135 Pin Windows CI version to 2019
  .github/actions/install-finance/action.yml
  .github/actions/install-main-dependencies/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
Labels: priority: high, type: ci

#137 Fix data provider docstring formatting
  qiskit_finance/data_providers/exchange_data_provider.py
  qiskit_finance/data_providers/random_data_provider.py
  qiskit_finance/data_providers/wikipedia_data_provider.py
  qiskit_finance/data_providers/yahoo_data_provider.py
Labels: stable backport potential, type: documentation

#138 Add circuit library documentation
  .pylintdict
  docs/apidocs/qiskit_finance.circuit.library.rst
  docs/apidocs/qiskit_finance.circuit.rst
  qiskit_finance/__init__.py
  qiskit_finance/circuit/__init__.py
  qiskit_finance/circuit/library/__init__.py
  qiskit_finance/circuit/library/payoff_functions/fixed_income_pricing_objective.py
  qiskit_finance/circuit/library/probability_distributions/lognormal.py
  qiskit_finance/circuit/library/probability_distributions/normal.py
  qiskit_finance/circuit/library/probability_distributions/uniform.py
Labels: stable backport potential, type: documentation
