Repository qiskit-community/qiskit-finance, pull requests merged in 2023-05, with the labels that each got.

#260 Pin ipython
  constraints.txt
Labels: stable backport potential, type: ci

#265 Terra main vs stable install switch
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: stable backport potential

#262 Update doc links and remove mailmap info from readme
  README.md
Labels: automerge

#264 Turn off CI for forks
  .github/workflows/main.yml
Labels: automerge

#270 Remove the `includenodoc` and `customcarditem` directives
  docs/conf.py
  docs/custom_directives.py
Labels: stable backport potential, type: documentation, automerge

#274 Update yahoo data provider unit test
  test/data_providers/test_data_providers.py
Labels: stable backport potential, priority: critical, automerge, type: ci

#273 Upgrade to qiskit_sphinx_theme 1.12
  docs/_static/no_image.png
  docs/conf.py
  docs/getting_started.rst
  docs/versionutils.py
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: stable backport potential, type: documentation, automerge

#281 Add project urls to setup
  setup.py
Labels: stable backport potential, automerge

#280 Update readme to use Sampler instead of now deprecated QuantumInstance
  README.md
Labels: automerge
