Repository qiskit-community/qiskit-finance, pull requests merged in 2023-04, with the labels that each got.

#253 Various docs changes for CI
  docs/conf.py
  requirements-dev.txt
  tox.ini
Labels: stable backport potential, type: documentation, automerge, type: ci

#256 Fix language toggle not working due to jQuery
  docs/_templates/page.html
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  requirements-dev.txt
Labels: stable backport potential, type: documentation

#258 Update intersphinx mappings
  docs/conf.py
Labels: stable backport potential, type: documentation, automerge
