Repository qiskit-community/qiskit-finance, pull requests merged in 2023-03, with the labels that each got.

#243 Update slack invite link
  README.md
Labels: automerge

#247 Fix a sentence in getting_started.rst
  docs/getting_started.rst
Labels: stable backport potential, type: documentation, automerge

#249 deploy documentation in qiskit.org/ecosystem
  tools/deploy_documentation.sh
Labels: stable backport potential, type: documentation, automerge, type: ci

#251 Revert path change in conf.py
  docs/conf.py
Labels: stable backport potential, automerge, type: ci
