Repository qiskit-community/qiskit-finance, pull requests merged in 2024-02, with the labels that each got.

#317 Fix compatibility/deprecations with newer Qiskit versions
  qiskit_finance/circuit/library/payoff_functions/european_call_pricing_objective.py
  qiskit_finance/circuit/library/probability_distributions/lognormal.py
  qiskit_finance/circuit/library/probability_distributions/normal.py
  requirements.txt
  test/circuit/test_probability_distributions.py
Labels: stable backport potential, automerge

#319 Update actions using deprecated Node.js
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: stable backport potential, automerge, type: ci

#321 Update intersphinx links and others
  README.md
  docs/conf.py
  docs/tutorials/00_amplitude_estimation.ipynb
  docs/tutorials/01_portfolio_optimization.ipynb
  docs/tutorials/02_portfolio_diversification.ipynb
  qiskit_finance/__init__.py
  qiskit_finance/data_providers/_base_data_provider.py
  qiskit_finance/data_providers/data_on_demand_provider.py
  qiskit_finance/data_providers/exchange_data_provider.py
  qiskit_finance/data_providers/wikipedia_data_provider.py
  qiskit_finance/data_providers/yahoo_data_provider.py
  setup.py
Labels: stable backport potential, type: documentation, automerge

#320 Add dependabot to manage future Github Actions updates
  .github/dependabot.yml
Labels: automerge, type: ci

#325 Remove remaining qiskit.org links
  CONTRIBUTING.md
  docs/getting_started.rst
  setup.py
Labels: stable backport potential, type: documentation

#328 Fix test_data_providers test_yahoo test
  test/data_providers/test_data_providers.py
Labels: stable backport potential

#327 Remove all other languages other than Spanish and Japanese
  docs/conf.py
Labels: stable backport potential, type: documentation

#331 Fix tutorials to work with Qiskit 1.0
  docs/tutorials/00_amplitude_estimation.ipynb
  docs/tutorials/01_portfolio_optimization.ipynb
  docs/tutorials/02_portfolio_diversification.ipynb
  docs/tutorials/03_european_call_option_pricing.ipynb
  docs/tutorials/04_european_put_option_pricing.ipynb
  docs/tutorials/05_bull_spread_pricing.ipynb
  docs/tutorials/06_basket_option_pricing.ipynb
  docs/tutorials/07_asian_barrier_spread_pricing.ipynb
  docs/tutorials/08_fixed_income_pricing.ipynb
  docs/tutorials/09_credit_risk_analysis.ipynb
  docs/tutorials/10_qgan_option_pricing.ipynb
  docs/tutorials/11_time_series.ipynb
  docs/tutorials/tutorial_magics.py
Labels: stable backport potential, type: documentation, automerge

#334 Add Python 3.12 support
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
  releasenotes/notes/py_3_12_support-b61ebb772bc24cb8.yaml
  setup.py
  tox.ini
Labels: stable backport potential, automerge
